### ISSUE TITLE
Strange behaviour on IE11

### ISSUE THREAD

**Issue by jasalguero** [funkensturm/ember-local-storage#47]
Hi,

I'm using the plugin to store a couple of simple values in local storage and it works all fine, except in IE (IE11), where there is no initial value set, and on changing (is a page size that I can change in an input) it gets in an infinite loop setting the variable to the new and initial value back and forth.

**Comment by fsmanuel** [comment]
@jasalguero I just did a quick google for 'IE11 localStorage' and it seems that the IE11 has a lot of problems with localStorage. What is the exact version number?

**Comment by fsmanuel** [comment]
@jasalguero can you try to debug the issue by removing these [lines](https://github.com/funkensturm/ember-local-storage/blob/master/addon/mixins/storage.js#L59-L65)?

**Comment by varoot** [comment]
I have the same issue with IE (10 and 11). Adding `if (document.hidden)` in the above section seems to fix the issue. This prevents the current tab from taking events fired from other (inactive) tabs, I guess.

**Comment by fsmanuel** [comment]
@varoot hmm but that would make the entire purpose of the storage event obsolete, doesn't it?

**Comment by fsmanuel** [comment]
@varoot wait! does your code look like:
```
    if (window.addEventListener && document.hidden) {
      window.addEventListener('storage', (event) => {
        if (event.key === storageKey) {
          this.set('content', JSON.parse(event.newValue));
        }
      });
    }
```

That would mean that the IE fires in the same tab the change occurred and that's why it results in an infinit loop. So it is the opposite of you guess but could be the fix.

**Comment by fsmanuel** [comment]
we might need a check `event.newValue !== event.oldValue` as well and probably a check if the `content !== JSON.parse(event.newValue)` before doing the set on content.

**Comment by krivaten** [comment]
Just found this in our app as well. According to [CanIUse](http://caniuse.com/#search=localstorage) "The storage event's oldValue and newValue are identical (newValue is supposed to contain the storage's updated value)". Not sure if that gives anyone aid, but trying to look in to this as well.

**Comment by varoot** [comment]
@fsmanuel No, my code is like this:

    if (window.addEventListener) {
        window.addEventListener('storage', (event) => {
            if (document.hidden && event.key === storageKey) {
                this.set('content', JSON.parse(event.newValue));
            }
        });
    }

which means that only hidden (inactive) tabs will take values. I think it makes sense since it's probably the active tab that sends out events in the first place.

You can look at my commit here: https://github.com/smartkarma/ember-local-storage/commit/1875172126b3e8e61800582c61c0ac55f2eb9dd8

**Comment by varoot** [comment]
The downside of this approach (that I can think of) is that `document.hidden` has less browser support than localStorage itself (compare [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) with [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API))

But for me this is acceptable, since it won't break the functionality even if the browser doesn't support `document.hidden`, it just won't propagate the changes from one tab to another, which is a lot better than just freezing IE.

**Comment by fsmanuel** [comment]
@varoot can you test if https://github.com/funkensturm/ember-local-storage/commit/660361900e6041ecc25dcb1dbe26a1b46b1bcfc7 fixes the issue?
I have no IE11 at hand to test it.

**Comment by varoot** [comment]
Yeah, it works. Tested on IE10 and IE11.

**Comment by fsmanuel** [comment]
I'll try to release the fix tomorrow.

**Comment by fsmanuel** [comment]
@jasalguero @krivaten @varoot I released `0.1.2`. Thanks for the feedback.

**Comment by MattNguyen** [comment]
This is still a problem if you call `set` multiple times within the same loop.

For example, we nest localStorage items for namespacing purposes, potentially calling `set` twice in total. 

```javascript
if (!storage.get('123')) { storage.set('123', {}) };
storage.set('123.john', { language: 'english' });
```

This in turn causes the storage change event to fire repeatedly:

```javascript
// first event
console.log(event.oldValue) // => null
console.log(event.newValue) // => { '123': {} }

// next event
console.log(event.oldValue) // => { '123': {} }
console.log(event.newValue) // => { '123': { john: { language: 'english } } }

// next event
console.log(event.oldValue) // => { '123': { john: { language: 'english } } }
console.log(event.newValue) // => { '123': {} }

// next event
console.log(event.oldValue) // => { '123': {} }
console.log(event.newValue) // => { '123': { john: { language: 'english } } }

// etc....
```

We ended up forking the lib and adding a check `document.hidden`, but as was mentioned previously, there's less support for the page visibility API than the web storage API.

Any ideas for a solution? Thanks!

**Comment by fsmanuel** [comment]
I'll investigate.

**Comment by fsmanuel** [comment]
@MattNguyen I released '0.1.3`.
